# Generated by Django 2.2.7 on 2020-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField(default=9898989898)),
                ('email', models.EmailField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
