# Generated by Django 2.0.2 on 2022-05-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_applicants_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='screenshot',
            field=models.ImageField(default='null', upload_to='media'),
        ),
    ]
