# Generated by Django 2.0.2 on 2022-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220524_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='course',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='applicants',
            name='no_of_logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicants',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
