# Generated by Django 2.0.2 on 2022-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20220529_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='verified',
        ),
        migrations.AddField(
            model_name='applicants',
            name='course',
            field=models.CharField(default='H', max_length=50),
        ),
    ]
