# Generated by Django 2.0.2 on 2022-05-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220529_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applicants',
            new_name='applicant',
        ),
    ]
